# Generated by Django 3.1 on 2021-11-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_jira_pages', '0003_userprojectworklogtablebydayspage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprojectworklogtablebydayspage',
            options={'ordering': ('-created_at',), 'verbose_name': 'Jira - Затраченное время пользователей и проектов (страница)', 'verbose_name_plural': 'Jira - Затраченное время пользователей и проектов (страница)'},
        ),
    ]
