# Generated by Django 3.1 on 2021-11-15 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0002_auto_20211101_1547'),
        ('garpix_jira_pages', '0004_auto_20211116_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializationWorklogTableByDaysPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Jira - Затраченное время пользователей и проектов (страница)',
                'verbose_name_plural': 'Jira - Затраченное время пользователей и проектов (страница)',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basepage',),
        ),
    ]
