# Generated by Django 3.1 on 2021-11-15 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_jira_pages', '0005_specializationworklogtablebydayspage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specializationworklogtablebydayspage',
            options={'ordering': ('-created_at',), 'verbose_name': 'Jira - Затраченное время специалистов по проектам (страница)', 'verbose_name_plural': 'Jira - Затраченное время специалистов по проектам (страница)'},
        ),
    ]
