# Generated by Django 3.1 on 2021-08-20 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_key', models.CharField(max_length=50, verbose_name='Ключ задачи')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('content', models.TextField(blank=True, default='', verbose_name='Содержимое')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, verbose_name='Логин')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
                ('server', models.CharField(default='https://jira.atlassian.com', max_length=200, verbose_name='Сервер jira')),
            ],
            options={
                'verbose_name': 'Сервер Jira',
                'verbose_name_plural': 'Серверы Jira',
                'ordering': ('server',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=512, verbose_name='Почта')),
                ('display_name', models.CharField(blank=True, default='', max_length=512, verbose_name='Отображаемое имя')),
                ('user_key', models.CharField(max_length=50, verbose_name='Ключ пользователя')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_jira.server', verbose_name='Сервер Jira')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent_seconds', models.IntegerField(default=0, verbose_name='Затрекано времени')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата/время записи журнала работ')),
                ('worklog_key', models.CharField(max_length=50, verbose_name='Ключ журнала работ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_worklogs', to='garpix_jira.user', verbose_name='Автор')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_jira.issue', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Журнал работ',
                'verbose_name_plural': 'Журналы работ',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0, verbose_name='ID проекта')),
                ('project_key', models.CharField(max_length=20, verbose_name='Ключ проекта')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_jira.server', verbose_name='Сервер Jira')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee_issues', to='garpix_jira.user', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='issue',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_issues', to='garpix_jira.user', verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_jira.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='issue',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter_issues', to='garpix_jira.user', verbose_name='Репортер'),
        ),
    ]
