# Generated by Django 3.1 on 2021-08-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_jira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_tracks_time',
            field=models.BooleanField(default=True, verbose_name='Пользователь трекает время?'),
        ),
    ]
