# Generated by Django 3.1 on 2021-12-02 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_jira', '0003_auto_20211115_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категории проектов Jira',
                'verbose_name_plural': 'Категории проектов Jira',
                'ordering': ('title',),
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Решение'),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата решения'),
        ),
        migrations.AddField(
            model_name='issue',
            name='time_estimate',
            field=models.IntegerField(default=0, verbose_name='Планово часов осталось'),
        ),
        migrations.AddField(
            model_name='issue',
            name='time_original_estimate',
            field=models.IntegerField(default=0, verbose_name='Первоначальная оценка'),
        ),
        migrations.AddField(
            model_name='issue',
            name='time_spent',
            field=models.IntegerField(default=0, verbose_name='Часов потрачено'),
        ),
        migrations.AddField(
            model_name='project',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивный'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garpix_jira.projectcategory', verbose_name='Категория'),
        ),
    ]
