# Generated by Django 3.1 on 2021-12-05 07:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_jira', '0004_auto_20211202_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='resolution_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата решения'),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('file', models.FileField(blank=True, null=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Файл')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_jira.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Документ для проекта Jira',
                'verbose_name_plural': 'Документы для проектов Jira',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlanEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('time_estimate_seconds', models.IntegerField(default=0, verbose_name='Эстимейт, секунды')),
                ('project_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_jira.projectdocument', verbose_name='Документ')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_jira.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Плановый эстимейт Jira',
                'verbose_name_plural': 'Плановые эстимейты Jira',
                'ordering': ('-created_at',),
            },
        ),
    ]
